# config/packages/messenger.yaml

framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

        routing:
            'App\MemoiresVivantes\Message\GenerateChapterMessage': async
            'App\ESG\Message\GenerateEsgReportMessage': async