# config/packages/monolog.yaml
monolog:
    # Déclare les canaux de logging que nous utiliserons
    channels: ['doctrine', 'security', 'deprecation']

    handlers:
        # -------------------------------------------------------------------
        # Handler principal pour l’environnement "default" (tous canaux sauf ceux exclus)
        # Ici, on exclut "event", "doctrine" et "security" pour ne pas mélanger les logs.
        # Les messages DEBUG+ seront écrits dans var/log/{env}.log
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: ["!event", "!doctrine", "!security","!deprecation"]

        # -------------------------------------------------------------------
        # Handler dédié aux requêtes Doctrine (SQL, cache, etc.)
        # Niveau WARNING afin de ne pas capturer chaque requête SQL exécutée en dev.
        doctrine:
            type:   stream
            path:   "%kernel.logs_dir%/dev-doctrine.log"
            level:  warning
            channels: ["doctrine"]

        # -------------------------------------------------------------------
        # Handler dédié au composant Security (firewalls, providers, voters, etc.)
        # Niveau INFO pour voir l’auth s’effectuer.
        security:
            type:   stream
            path:   "%kernel.logs_dir%/dev-security.log"
            level:  info
            channels: ["security"]

        # -------------------------------------------------------------------
        # Handler pour le canal "deprecation"
        # Permet de capturer toutes les dépréciations dans un fichier dédié au niveau ERROR uniquement.
        deprecation:
            type:   stream
            path:   "%kernel.logs_dir%/deprecations.log"
            level:  error
            channels: ["deprecation"]

        # -------------------------------------------------------------------
        # Handler "console" pour afficher certains logs en CLI
        # On exclut "event", "doctrine" et "security" pour ne pas polluer la console.
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!security"]

when@prod:
    monolog:
        handlers:
            # Ce handler va écraser tous les autres handlers définis plus haut,
            # mais uniquement lorsque l'environnement est 'prod'.
            main:
                type: stream
                path: "php://stderr" # On envoie tout vers la sortie d'erreur du conteneur
                level: debug      # On log tout pour le débogage
                formatter: monolog.formatter.json
