# config/packages/monolog.yaml
monolog:
    # Déclare les canaux de logging que nous utiliserons
    channels: ['doctrine', 'security', 'deprecation']

    handlers:
        # -------------------------------------------------------------------
        # Handler principal pour l’environnement "default" (tous canaux sauf ceux exclus)
        # Ici, on exclut "event", "doctrine" et "security" pour ne pas mélanger les logs.
        # Les messages DEBUG+ seront écrits dans var/log/{env}.log
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!doctrine", "!security","!deprecation"]

        # -------------------------------------------------------------------
        # Handler dédié aux requêtes Doctrine (SQL, cache, etc.)
        # Niveau DEBUG afin de capturer chaque requête SQL exécutée.
        doctrine:
            type:   stream
            path:   "%kernel.logs_dir%/dev-doctrine.log"
            level:  debug
            channels: ["doctrine"]

        # -------------------------------------------------------------------
        # Handler dédié au composant Security (firewalls, providers, voters, etc.)
        # Niveau DEBUG pour voir quel firewall est matché et comment l’auth s’effectue.
        security:
            type:   stream
            path:   "%kernel.logs_dir%/dev-security.log"
            level:  debug
            channels: ["security"]

        # -------------------------------------------------------------------
        # Handler pour le canal "deprecation"
        # Permet de capturer toutes les dépréciations dans un fichier dédié.
        deprecation:
            type:   stream
            path:   "%kernel.logs_dir%/deprecations.log"
            level:  debug
            channels: ["deprecation"]

        # -------------------------------------------------------------------
        # Handler "console" pour afficher certains logs en CLI
        # On exclut "event", "doctrine" et "security" pour ne pas polluer la console.
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!security"]
