nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'DELETE', 'PUT', 'PATCH']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': ~
