security:
    
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        tenant_user_provider:
            id: App\Security\TenantUserProvider
    firewalls:



        api:
            pattern:   ^/api(?!/(login|tenant/check))
            stateless: true
            provider:  tenant_user_provider
            jwt: ~


        dev:
            pattern:   ^/(_(profiler|wdt)|css|images|js)/
            security:  false

        gemsuite_api:

            pattern: ^/api/webhook/gemsuite
            
            stateless: true
            
            custom_authenticators:
                - App\Security\GemsuiteJwtAuthenticator

        main:
            pattern:                ^/             # prend tout le reste
            stateless:              false          # si vous utilisez des sessions
            provider:               tenant_user_provider  # ← impératif !
            custom_authenticator:   App\Security\LoginAuthenticator
            logout:
                path: app_logout
            user_checker:           App\Security\UserChecker
        


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # 🔹 ROLE_USER_INTERNET peut lire (GET)
        - { path: ^/api/admin-settings, methods: [GET], roles: PUBLIC_ACCESS }
        # 🔹 ROLE_ADMIN peut modifier (POST, PUT, DELETE)
        - { path: ^/api/admin-settings, methods: [POST, PUT, DELETE], roles: ROLE_ADMIN }

        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(account|adress|checkout), roles: [ROLE_USER_INTERNET, ROLE_USER_POS,ROLE_ADMIN] }
        - { path: ^/api/(login|register|login-web|token/refresh|password-reset/request|password-reset/confirm|password-reset/form|products/by-category|category|homeslider|products|entreprise|otp-verify|features|explore-cards|webhooks/gemsuite|bannieres|emplois|candidatures|marques|categories-marque|multiliens|recherches|service-offers|videos|contacts|components-config|landingpage-settings|embeds|baniere-statiques|presentations|landingpage|presentation-groups|tenant/check|newsletter/subscribe|booking|resend-verification), roles: PUBLIC_ACCESS }
        - { path: ^/api/(collections|createcollections|commandes|fournisseurs|transporteurs|dashboard|caisse|statistiques|stock-evolution|stock-value|frais|payments/statistics|taxes/monthly|carrier/statistics), roles: ROLE_ADMIN }
        - { path: ^/api, roles: [ROLE_USER_INTERNET, ROLE_USER_POS,ROLE_ADMIN] }

        



when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
