# docker-compose.yml

version: '3.8'

services:
  app:
    image: ghcr.io/${CLIENT1_GITHUB_REPOSITORY_OWNER}/symfony-backend:latest
    container_name: symfony_app
    volumes:
      - public_data:/var/www/public
      - ./jwt:/var/www/config/jwt
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - symfony
    restart: always
    healthcheck:
      disable: true

  db:
    image: postgres:15
    container_name: symfony_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony
    healthcheck:
      disable: true

  redis:
    image: redis:7
    container_name: redis_cache
    restart: unless-stopped
    networks:
      - symfony
    volumes:
      - redis_data:/data

  # --- MODIFICATIONS ICI ---
  nginx:
    image: ghcr.io/${CLIENT1_GITHUB_REPOSITORY_OWNER}/symfony-nginx:latest
    container_name: symfony_nginx
    # On expose les ports directement sur Nginx
    ports:
      - "0.0.0.0:8443:80"
    volumes:
      - public_data:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      - /etc/ssl/caddy/64.187.182.48.pem:/etc/ssl/certs/64.187.182.48.pem:ro
      - /etc/ssl/caddy/64.187.182.48-key.pem:/etc/ssl/private/64.187.182.48-key.pem:ro
    networks:
      - symfony
    depends_on:
      - app
    restart: always
  # --- FIN DES MODIFICATIONS ---

  worker-1:
    image: ghcr.io/${CLIENT1_GITHUB_REPOSITORY_OWNER}/symfony-backend:latest
    container_name: symfony_worker_1
    command: php bin/console messenger:consume async_worker_1 -vv
    volumes:
      - public_data:/var/www/public
      - ./jwt:/var/www/config/jwt
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - symfony
    restart: always
    depends_on:
      - redis
      - db

  worker-2:
    image: ghcr.io/${CLIENT1_GITHUB_REPOSITORY_OWNER}/symfony-backend:latest
    container_name: symfony_worker_2
    command: php bin/console messenger:consume async_worker_2 -vv
    volumes:
      - public_data:/var/www/public
      - ./jwt:/var/www/config/jwt
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - symfony
    restart: always
    depends_on:
      - redis
      - db

  worker-3:
    image: ghcr.io/${CLIENT1_GITHUB_REPOSITORY_OWNER}/symfony-backend:latest
    container_name: symfony_worker_3
    command: php bin/console messenger:consume async_worker_3 -vv
    volumes:
      - public_data:/var/www/public
      - ./jwt:/var/www/config/jwt
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - symfony
    restart: always
    depends_on:
      - redis
      - db

volumes:
  db_data:
  redis_data:
  public_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${CLIENT1_SERVER_USER}/app/public

networks:
  symfony:
    driver: bridge