# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $gemsuiteApiUrl: '%env(resolve:GEMSUITE_API_URL)%'

    Doctrine\ORM\Configuration: '@doctrine.orm.default_configuration'
    Doctrine\Common\EventManager: '@doctrine.dbal.default_connection.event_manager'    

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Repository/UserRepository.php'
            - '../src/Repository/AdressRepository.php'
            - '../src/Repository/AdminSettingsRepository.php'
            - '../src/Repository/EasyPostConfigurationRepository.php'
            - '../src/Repository/CaisseRepository.php'
            - '../src/Repository/TransactionCaisseRepository.php'
            - '../src/Repository/TransactionTypeRepository.php'
            - '../src/Repository/TypeCashRepository.php'
            - '../src/Repository/OrderRepository.php'
            - '../src/Repository/CashDetailsRepository.php'
            - '../src/Repository/CarrierRepository.php'
            - '../src/Repository/ProductRepository.php'
            - '../src/Repository/CategoriesRepository.php'
            - '../src/Repository/CollectionsRepository.php'
            - '../src/Repository/CollectionPictureRepository.php'
            - '../src/Repository/ColorRepository.php'
            - '../src/Repository/CommandeRepository.php'
            - '../src/Repository/FournisseurRepository.php'
            - '../src/Repository/TypeFournisseurRepository.php'
            - '../src/Repository/CommandeStatistiquesRepository.php'
            - '../src/Repository/CollectionStatistiquesRepository.php'
            - '../src/Repository/ExploreCardRepository.php'
            - '../src/Repository/FeatureRepository.php'
            - '../src/Repository/FraisDePortRepository.php'
            - '../src/Repository/TransporteurRepository.php'
            - '../src/Repository/NoteDeFraisRepository.php'
            - '../src/Repository/TypeNoteDeFraisRepository.php'
            - '../src/Repository/OrderTaxRepository.php'
            - '../src/Repository/TaxRepository.php'
            - '../src/Repository/StatusCommandeRepository.php'
            - '../src/Repository/OrderSourceRepository.php'
            - '../src/Repository/OrderTypeRepository.php'
            - '../src/Repository/PaymentsRepository.php'
            - '../src/Repository/PaymentMethodRepository.php'
            - '../src/Repository/PaymentTypeRepository.php'
            - '../src/Repository/StatusPaymentRepository.php'
            - '../src/Repository/OrderItemsRepository.php'
            - '../src/Repository/ProductVariantRepository.php'
            - '../src/Repository/MovementTypeRepository.php'
            - '../src/Repository/SquareConfigRepository.php'
            - '../src/Repository/StyleRepository.php'
            - '../src/Repository/SizeRepository.php'
            - '../src/Repository/ProductShippingRepository.php'
            - '../src/Repository/PackagingTypeRepository.php'
            - '../src/Repository/ShippingOrderRepository.php'
            - '../src/Repository/ParcelRepository.php'
            - '../src/Repository/ShippingLabelRepository.php'
            - '../src/Repository/AddressEntrepriseRepository.php'
            - '../src/Repository/ContactRepository.php'
            - '../src/Repository/GooglePlacesConfigRepository.php'
            - '../src/Repository/OrderDetailsRepository.php'
            - '../src/Repository/RelatedProductRepository.php'
            - '../src/Repository/ReviewsProductRepository.php'
            - '../src/Repository/ShippingClassRepository.php'
            - '../src/Repository/ProductOptionRepository.php'
            - '../src/Repository/ProductOptionValueRepository.php'
            - '../src/Repository/SaleUnitRepository.php'
            - '../src/Repository/RentalPackRepository.php'


            

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Add the JWTCreatedListener service
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\EventListener\JWTFromCookieListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }


    App\EventSubscriber\CacheInvalidationSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Services\TenantConnectionManager:
        arguments:
            $masterDatabaseUrl: '%env(MASTER_DATABASE_URL)%'
            $defaultTenantUrl:  '%env(DATABASE_URL)%'
            $projectDir:        '%kernel.project_dir%'
            $connection:        '@doctrine.dbal.default_connection'

       
    App\Services\TenantConnectionProvider:
        public: true
        shared: true


    App\Services\TenantEntityManagerProvider:
        public: true
        shared: true



    # Exemple pour TokenService :
    App\Services\TokenService:
        arguments:
            $JWTManager:    '@lexik_jwt_authentication.jwt_manager'
   

    App\EventListener\TenantDoctrineSwitcherListener:
        arguments:
            # On a supprimé $masterDatabaseUrl et $frontendMainDomain qui ne servent plus
            $backendMainDomain: '%env(resolve:BACKEND_BASE_DOMAIN)%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

      
    App\Repository\ResetPasswordRequestRepository:
        tags: ['doctrine.repository_service']  


    App\Command\ExecuteSingleTenantMigrationCommand:
        bind:
            $projectDir: '%kernel.project_dir%'


    App\Security\GemsuiteJwtAuthenticator:
        arguments:
            # Bind the constructor argument '$projectDir' to the container parameter '%kernel.project_dir%'
            $projectDir: '%kernel.project_dir%'
            
    App\Command\CleanMigrationHistoryCommand:
        bind:
            $projectDir: '%kernel.project_dir%'

    App\Services\DeepLTranslateService\DeepLTranslateService:
        arguments:
            $deepLApiKey: '%env(DEEPL_API_KEY)%'

    App\Controller\TenantSetupController\TenantSetupController:
        bind:
            $frontendBaseDomain: '%env(FRONTEND_BASE_DOMAIN)%'

    App\Services\GoogleTranslateService\GoogleTranslateService:
        arguments:
            $googleApiKey: '%env(GOOGLE_API_KEY)%'        

    App\Services\StripeService\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%' 

    App\Services\StripePaymentService\StripePaymentService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'       

    App\Services\ShippingService\EasyPostService:
        arguments:
            $appEnv: '%kernel.environment%'

    App\Controller\TenantSetupController\TenantController:
        arguments:
            $frontendBaseDomain: '%env(resolve:FRONTEND_BASE_DOMAIN)%'
            $backendBaseDomain: '%env(resolve:BACKEND_BASE_DOMAIN)%'