# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Doctrine\ORM\Configuration: '@doctrine.orm.default_configuration'
    Doctrine\Common\EventManager: '@doctrine.dbal.default_connection.event_manager'    

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Repository/UserRepository.php'
            - '../src/Repository/GooglePlacesConfigRepository.php'
            - '../src/Repository/AdressRepository.php'
            - '../src/Repository/AdminSettingsRepository.php'
            - '../src/Repository/EasyPostConfigurationRepository.php'
            - '../src/Repository/CaisseRepository.php'
            - '../src/Repository/TransactionCaisseRepository.php'
            - '../src/Repository/TransactionTypeRepository.php'
            - '../src/Repository/TypeCashRepository.php'
            - '../src/Repository/OrderRepository.php'
            - '../src/Repository/CashDetailsRepository.php'
            - '../src/Repository/CarrierRepository.php'
            - '../src/Repository/ProductRepository.php'
            - '../src/Repository/CategoriesRepository.php'
            - '../src/Repository/CollectionsRepository.php'
            - '../src/Repository/CollectionPictureRepository.php'
            - '../src/Repository/ColorRepository.php'
            - '../src/Repository/CommandeRepository.php'
            - '../src/Repository/FournisseurRepository.php'
            - '../src/Repository/TypeFournisseurRepository.php'
            - '../src/Repository/CommandeStatistiquesRepository.php'

            

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Add the JWTCreatedListener service
    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    App\EventListener\JWTFromCookieListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10 }


    App\EventSubscriber\CacheInvalidationSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\Services\TenantConnectionManager:
        arguments:
            $masterDatabaseUrl: '%env(MASTER_DATABASE_URL)%'
            $defaultTenantUrl:  '%env(DATABASE_URL)%'
            $projectDir:        '%kernel.project_dir%'
            $connection:        '@doctrine.dbal.default_connection'

       
    App\Services\TenantConnectionProvider:
        public: true
        shared: true


    App\Services\TenantEntityManagerProvider:
        public: true
        shared: true



    # Exemple pour TokenService :
    App\Services\TokenService:
        arguments:
            $JWTManager:    '@lexik_jwt_authentication.jwt_manager'
   

    App\Services\TenantDoctrineSwitcherListener:
        arguments:
            $masterDatabaseUrl: '%env(resolve:MASTER_DATABASE_URL)%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 250 }

      
    App\Repository\ResetPasswordRequestRepository:
        tags: ['doctrine.repository_service']  


    App\Repository\GooglePlacesConfigRepository:
        tags: ['doctrine.repository_service']