api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: michel.almont972@gmail.com  # Votre adresse email
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

middlewares:
  secure-dashboard:
    basicAuth:
      users:
        - "admin:$2y$05$lfmjn5OCwnYruXb9q3eqE.5KFfO3XjUyQfPlwK3o5HIyYqu86S9B2" 