version: '3.8'

services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.symfony.rule=Host(`srv690974.hstgr.cloud`)"
      - "traefik.http.routers.symfony.entrypoints=websecure"
      - "traefik.http.routers.symfony.tls.certresolver=letsencrypt"
